data_dir: data/4D5_HER2_fitness_1N8Z/ablang2/greedy
pdb_file: pdbs/1N8Z.pdb
seed: 42
flx_num: 1
max_cycles: 10
mutable_chain: H
wildtype_sequence:
  H: EVQLVESGGGLVQPGGSLRLSCAASGFNIKDTYIHWVRQAPGKGLEWVARIYPTNGYTRYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCSRWGGDGFYAMDYWGQGTLVTVSS
mask_indices:
- 96
- 97
- 98
- 99
- 100
- 101
- 102
- 103
- 104
- 105
- 106
- 107
- 108
POI: 1N8Z
mutations_col: mutations
early_stop_patience: 20
n_steps: 1000
generation:
  generation_mode: esm_sampling
  generation_num: 100000
  temperature: 1.0
  normalize_mode: default
  ensemble_mode: true
  ensemble_num: 10
  online_generation: true
  bias: true
  generation_file: sampling/4D5_HER2_fitness_1N8Z/ablang2/bias/generation_result.csv
acquisition:
  strategy_name: greedy
  acquisition_num: 40
lora_config:
  target_modules:
  - q_proj
  - k_proj
  - v_proj
  - out_proj
  - lm_head.dense
  modules_to_save: []
  inference_mode: false
  lora_dropout: 0.1
  lora_alpha: 8
light_wt_sequence: DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQYFRMPPGFGQGTKVEIK
model_type: ablang2
