[project]
name = "allm-ab-env"
version = "0.1.0"
description = "Environment for ALLM-Ab"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "ablang2>=0.2.1",
    "biopython>=1.85",
    "easydict>=1.13",
    "fair-esm>=2.0.0",
    "jupyterlab>=4.4.3",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "peft>=0.15.2",
    "pygmo>=2.19.5",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.7.0",
    "scipy>=1.16.0",
    "torch==2.7.0",
    "torch-geometric>=2.6.1",
    "torch-scatter",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
torch-scatter = { url = "https://data.pyg.org/whl/torch-2.7.0%2Bcu128/torch_scatter-2.1.2%2Bpt27cu128-cp311-cp311-linux_x86_64.whl" }
